# Generated by Django 3.1.3 on 2020-11-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trademark_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trademark_api.user')),
                ('username', models.CharField(max_length=30)),
                ('currentBalance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
