# Generated by Django 3.1.1 on 2020-09-29 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trademark_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='M', max_length=1)),
                ('order_type', models.CharField(choices=[('M', 'Market'), ('L', 'Limit')], default='M', max_length=1)),
                ('execution_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('time_in_force', models.CharField(choices=[('GFD', 'Good For Day'), ('GTC', 'Good Till Cancelled'), ('IOC', 'Immediate or Cancel'), ('FOK', 'Fill or Kill')], default='GFD', max_length=3)),
                ('filled', models.BooleanField(default=False)),
                ('filled_at', models.DateTimeField(default=None, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
